services:
  db:
    image: postgres:16
    container_name: crm-postgres
    restart: always
    environment:
      POSTGRES_USER: crmuser
      POSTGRES_PASSWORD: crmpassword
      POSTGRES_DB: crmdb
    ports:
      - "5432:5432"